#!/bin/bash

. /srv/http/bash/common.sh

for file in /etc/X11/xinit/xinitrc.d/*; do
	. "$file"
done

$dirsettings/features.sh localbrowserxset

if [[ ! $( ipAddress ) ]] || grep -q cursor=true /srv/http/data/system/localbrowser.conf; then
	cursor=yes
else
	cursor=no
fi
matchbox-window-manager -use_cursor $cursor &
firefox -kiosk -private http://localhost
