#!/bin/bash

export XDG_CACHE_HOME="/tmp/.cache"

. /srv/http/data/system/localbrowser.conf

/srv/http/bash/settings/features.sh localbrowserxset

if ifconfig | grep -q broadcast; then
	[[ $cursor == false ]] && cursor=no || cursor=yes
else # no network connection
	cursor=yes
fi
matchbox-window-manager -use_cursor $cursor &

zoom=$( echo "print $zoom / 100" | perl )
[[ $zoom != 1 ]] && scalefactor="--force-device-scale-factor=$zoom"
chromium localhost $scalefactor \
	--disable-software-rasterizer \
	--incognito \
	--kiosk \
	--no-sandbox
