#!/bin/bash

mkdir -p /tmp/.cache

export XDG_CACHE_HOME=/tmp/.cache

for file in /etc/X11/xinit/xinitrc.d/*; do
	. "$file"
done

. /srv/http/data/system/localbrowser.conf

/srv/http/bash/settings/features.sh localbrowserxset

if ifconfig | grep -q broadcast; then
	[[ $cursor == false ]] && cursor=no || cursor=yes
else # no network connection
	cursor=yes
fi
zoom=$( echo "print $zoom / 100" | perl )
[[ $zoom != 1 ]] && scalefactor=--force-device-scale-factor=$zoom

matchbox-window-manager -use_cursor $cursor &

chromium localhost $scalefactor \
	--disable-software-rasterizer \
	--incognito \
	--kiosk \
	--no-sandbox
